// <auto-generated />
using System;
using Persistence.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Persistence.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220822202237_Mig08_ModifyDbStructure_0822")]
    partial class Mig08_ModifyDbStructure_0822
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Persistence.Entities.SuperHero", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Place")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("SuperHeroes");
                });

            modelBuilder.Entity("Persistence.Entities.T_COMPANY", b =>
                {
                    b.Property<int>("F_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_ID"), 1L, 1);

                    b.Property<string>("F_AccountNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("F_AccountingContact")
                        .HasColumnType("int");

                    b.Property<string>("F_Addr")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("F_BondNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("F_City")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_Country")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("F_CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("F_CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_Credential")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<float?>("F_CreditLimit")
                        .HasColumnType("real");

                    b.Property<int?>("F_DeliveryContact")
                        .HasColumnType("int");

                    b.Property<string>("F_EMAIL")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("F_FAX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_FName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("F_Group")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("F_IATANo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("F_IRSNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_IRSType")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("F_OfficeContact")
                        .HasColumnType("int");

                    b.Property<string>("F_PIMSCNTRY")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("F_PIMSID")
                        .HasColumnType("int");

                    b.Property<int?>("F_PIMSRPARTY")
                        .HasColumnType("int");

                    b.Property<string>("F_PIMSTYPE")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("F_Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("F_PickUpContact")
                        .HasColumnType("int");

                    b.Property<string>("F_SName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("F_STATUS")
                        .HasColumnType("int");

                    b.Property<string>("F_State")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<int?>("F_Terms")
                        .HasColumnType("int");

                    b.Property<int?>("F_UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("F_UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_Website")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("F_ZipCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("F_ID");

                    b.ToTable("T_COMPANY");
                });

            modelBuilder.Entity("Persistence.Entities.T_CONTAINER", b =>
                {
                    b.Property<int>("F_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_ID"), 1L, 1);

                    b.Property<DateTime?>("F_ATA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("F_ATD")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_BLNO")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<DateTime?>("F_BookingDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_BookingNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("F_Carrier")
                        .HasColumnType("int");

                    b.Property<string>("F_Commodity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("F_ConType")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("F_ContainerNo")
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.Property<DateTime?>("F_CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("F_CreatedUser")
                        .HasColumnType("int");

                    b.Property<string>("F_HSCODE")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("F_KGSLBS")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("F_LastFreeDay")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("F_LoadDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_Memo")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<int?>("F_PKGS")
                        .HasColumnType("int");

                    b.Property<string>("F_PickupNo")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("F_PickupPlace")
                        .HasMaxLength(60)
                        .HasColumnType("nvarchar(60)");

                    b.Property<string>("F_SealNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("F_TableId")
                        .HasColumnType("int");

                    b.Property<string>("F_TableName")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("F_UnloadDate")
                        .HasColumnType("datetime2");

                    b.HasKey("F_ID");

                    b.ToTable("T_CONTAINER");
                });

            modelBuilder.Entity("Persistence.Entities.T_FILEMAIN", b =>
                {
                    b.Property<int>("F_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_ID"), 1L, 1);

                    b.Property<string>("F_APIKEY")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("F_BLNO")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("F_CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("F_DeletedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_FILENAME")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("F_FILEPATH")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("F_FILESTATUS")
                        .HasColumnType("int");

                    b.Property<int?>("F_FILETYPE")
                        .HasColumnType("int");

                    b.Property<string>("F_JSON")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_RefNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("F_TableId")
                        .HasColumnType("int");

                    b.Property<string>("F_TableName")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("F_UploadTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("F_UserId")
                        .HasColumnType("int");

                    b.Property<string>("F_UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("F_ID");

                    b.ToTable("T_FILEMAIN");
                });

            modelBuilder.Entity("Persistence.Entities.T_OIHMAIN", b =>
                {
                    b.Property<int>("F_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_ID"), 1L, 1);

                    b.Property<string>("F_AMSBLNO")
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("F_BName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("F_Broker")
                        .HasColumnType("int");

                    b.Property<int?>("F_CFSLocation")
                        .HasColumnType("int");

                    b.Property<string>("F_CName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("F_CYLocation")
                        .HasColumnType("int");

                    b.Property<string>("F_ClosedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("F_Commodity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("F_Consignee")
                        .HasColumnType("int");

                    b.Property<string>("F_CustRefNo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("F_Customer")
                        .HasColumnType("int");

                    b.Property<string>("F_DcodeCustom")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<float?>("F_DefaultRate")
                        .HasColumnType("real");

                    b.Property<string>("F_Description")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("F_ExpRLS")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<DateTime?>("F_FETA")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_FcodeCustom")
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<string>("F_FileClosed")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("F_ForeignDest")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("F_HBLNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_HSCODE")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int?>("F_INVOICETO")
                        .HasColumnType("int");

                    b.Property<string>("F_ISFNO")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_Mark")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("F_MarkGross")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("F_MarkMeasure")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("F_MarkPkg")
                        .HasMaxLength(800)
                        .HasColumnType("nvarchar(800)");

                    b.Property<string>("F_Memo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("F_MoveType")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("F_NName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("F_Nomi")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("F_Notify")
                        .HasColumnType("int");

                    b.Property<int?>("F_OIMMAINID")
                        .HasColumnType("int");

                    b.Property<string>("F_PPCC")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<DateTime?>("F_PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_SName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("F_Shipper")
                        .HasColumnType("int");

                    b.Property<int?>("F_TotalContainer")
                        .HasColumnType("int");

                    b.HasKey("F_ID");

                    b.ToTable("T_OIHMAIN");
                });

            modelBuilder.Entity("Persistence.Entities.T_OIMMAIN", b =>
                {
                    b.Property<int>("F_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_ID"), 1L, 1);

                    b.Property<int?>("F_Agent")
                        .HasMaxLength(100)
                        .HasColumnType("int");

                    b.Property<string>("F_AgentName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("F_AgentRefNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("F_BName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("F_Broker")
                        .HasColumnType("int");

                    b.Property<string>("F_CName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("F_Carrier")
                        .HasColumnType("int");

                    b.Property<string>("F_CarrierName")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("F_ClosedBy")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("F_Consignee")
                        .HasColumnType("int");

                    b.Property<int?>("F_DCode")
                        .HasColumnType("int");

                    b.Property<string>("F_DisCharge")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("F_ETA")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("F_ETD")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_ExpRLS")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("F_FCode")
                        .HasColumnType("int");

                    b.Property<DateTime?>("F_FETA")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_FeederVessel")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("F_FileClosed")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<string>("F_FinalDelivery")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("F_FinalDest")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("F_ITDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_ITNo")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<string>("F_ITPlace")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_LCLFCL")
                        .HasMaxLength(1)
                        .HasColumnType("nvarchar(1)");

                    b.Property<int?>("F_LCode")
                        .HasColumnType("int");

                    b.Property<string>("F_LoadingPort")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("F_MBLNo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_Memo")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("F_MoveType")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("F_NName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("F_Notify")
                        .HasColumnType("int");

                    b.Property<string>("F_PPCC")
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.Property<string>("F_PaidPlace")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime?>("F_PostDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_RefNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_SMBLNo")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_SName")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("F_SVCCNo")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("F_Shipper")
                        .HasColumnType("int");

                    b.Property<int?>("F_TotalContainer")
                        .HasColumnType("int");

                    b.Property<string>("F_Vessel")
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("F_Voyage")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("F_mCommodity")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("F_ID");

                    b.ToTable("T_OIMMAIN");
                });

            modelBuilder.Entity("Persistence.Entities.T_USER", b =>
                {
                    b.Property<int>("F_ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("F_ID"), 1L, 1);

                    b.Property<int?>("F_CompanyId")
                        .HasColumnType("int");

                    b.Property<int?>("F_CreateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("F_CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_Dept")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("F_FAX")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("F_LastLogin")
                        .HasColumnType("datetime2");

                    b.Property<int?>("F_Level")
                        .HasColumnType("int");

                    b.Property<string>("F_Phone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("F_Status")
                        .HasColumnType("int");

                    b.Property<int?>("F_UpdateBy")
                        .HasColumnType("int");

                    b.Property<DateTime?>("F_UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("F_UserEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("F_UserId")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("F_UserName")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("F_UserPwd")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("F_ID");

                    b.ToTable("T_USER");
                });
#pragma warning restore 612, 618
        }
    }
}
